# Generated by Django 2.2.6 on 2019-10-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolar',
            fields=[
                ('fecha', models.DateTimeField(primary_key=True, serialize=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
